export const Search = () => null
export const Star = () => null
export const Bookmark = () => null
export const BookmarkCheck = () => null
export const Trash2 = () => null
export const X = () => null
export const ChevronRight = () => null
export const Info = () => null
export const AlertCircle = () => null
export const Check = () => null